### PR TITLE
[Option A] Make fatal able to panic, preventing error log overridding

### PR DESCRIPTION
**Pull request by KolbyML**
Currently if someone writes a hivesim-rs test and report a failure with test.fatal() they can easily override the previous error which is bad practice. If fatal is called the test should be seen as done and not continue running.

Before this pr if you did
```
test.fatal("A");
test.fatal("B");
```
"B" would be the error in the test log

After this PR if the same example was ran as above instead this error will be there
``"Error: test overrides previous failure log, potential solution add return statement after 'test.fatal()' call"``

Adding this change prevents/warns us if a bad case like this ever occurs. The reason it is bad since most likely error A will be the cause of Error B, so it shouldn't be overridden. To list one argument for this change.

### CODE REVIEW

**Review by kdeme — COMMENTED** [review]
Perhaps I misunderstand what occurs now, but wouldn't it be better to stop the test (and fail) immediatly on the `self.fail()` ?

**Comment by KolbyML** [comment]
> Perhaps I misunderstand what occurs now, but wouldn't it be better to stop the test (and fail) immediatly on the `self.fail()` ?

I agree that would be nice. Currently tests are only stopped on "returns", which is why that value can be potentially be overridded if someone forgets to add a return statement. I am looking for a quick solution, since something like that would require rewriting a bit of code I believe. I want a solution that prevents bad behaviors, but I also want to focus on debugging Trin rn.

So I would propose this as a quick solution to prevent/warn against bad behavior which we can merge now.
Then we can make a issue or add a todo, to eventually do that rewrite which makes it cleaner/simpler to write tests, without worrying about a issue like this being possible.

**Comment by ogenev** [comment]
I would prefer to solve the underlying issue before merging, instead of adding temporary `fixes`. For local testing, we don't need to merge it to the main branch.

I think in this case it is good to look into the reference implementation, which is the go library `hivesim`.

As we can see [here](https://github.com/ethereum/portal-hive/blob/406248c49333c9d2b6312aa2b46a4d64e7c8e994/hivesim/testapi.go#L238), `t.Fatal` logs the error and run `t.FailNow` method:

https://github.com/ethereum/portal-hive/blob/406248c49333c9d2b6312aa2b46a4d64e7c8e994/hivesim/testapi.go#L284

`FailNow`  makes the test pass result to `false` **and** calls `runtime.Goexit()` which exits the current goroutine.

`runtime.Goexit()`  is the missing part in our implementation and it is a bug, we need to exit the current tokio thread without panicking the whole process. 

I would check if all tests run in separate tokio threads and if this is the case, then panic inside `fail` would terminate the current test on failure without exiting the whole simulator.

**Comment by KolbyML** [comment]
I found the issue with trin failing #61 quicker then I thought so I will get to work on this fix now @ogenev

**Comment by KolbyML** [comment]
@ogenev ok I implemented the functionality you mentioned. I basically wrapped the (func)(x, y) calls in tokio threads so if a panic happens it doesn't affect the rest of the program.

So this PR is ready to review again.

**Comment by KolbyML** [comment]
Closing this PR with https://github.com/ethereum/portal-hive/pull/67 since I think that solution is cleaner

**Pull request closed without merging**
