### PR TITLE
feat: remove rust simulators portal hive -> hive

### PR DESCRIPTION
**Pull request by KolbyML**
>All of the Rust Portal-Hive simulators are now located on ethereum/hive so maybe in a month or so am going to remove them from portal-hive. We will still be maintaining hivesim-rs on ethereum/portal-hive for the time being, but eventually we will look into moving that over too. 
Felix has been sharing cool insights with me already and ethereum/hive is nice because it has all the upstream work/features in it already. So it is very cool this collaboration was made possible 👍 
One of the key cool notes is this enables of to include EL clients into our portal hive tests. I haven't looked fully into the complexity or challenges of doing this yet, but it is very cool it is now a possibility

^ this is my message I posted on the portal network discord in the portal-hive channel.

We will be no longer maintaining rust simulators in this repo and instead doing it on ethereum/hive.

### CODE REVIEW

**Comment by ogenev** [comment]
Should we update also the CI jobs?

**Comment by KolbyML** [comment]
Yes

**Review by ogenev — APPROVED** [review]
🛥️

**Comment by KolbyML** [comment]
They are now deployed on https://portal-hive.ethdevops.io/ https://github.com/ethereum/hive so I am going to merge this

**Pull request merged**
