### PR TITLE
change rpc-compat sim to use isolated client per test

### PR DESCRIPTION
**Pull request by KolbyML**
This PR redesigns ``rpc-compat``  to start a fresh client image each test

### CODE REVIEW

**Comment by KolbyML** [comment]
The CI should pass, the issue is I modified both ``hivesim-rs`` and a simulator. Since the simulator only pulls from ethereum/portal-hive master it doesn't have the changes from ``hivesim-rs`` in this PR

**Comment by ogenev** [comment]
Blocked by #44 .

**Comment by ogenev** [comment]
@KolbyML could you please rebase before the final review?

**Comment by KolbyML** [comment]
@ogenev ok I rebased it again, it should be ready for you now

**Review by ogenev — APPROVED** [review]
Looks good :+1:

**Pull request merged**
