### PR TITLE
Copy over Cargo.lock files in docker builds

### PR DESCRIPTION
**Pull request by KolbyML**
This fixes a issue where when we update ethportal-api portal-hive will fail on us.

This will now require us to update ethportal-api in the lockfile if we want the new changes and prevent portal-hive randomly breaking. Since currently we pull the latest ethportal-api from git.

### CODE REVIEW

**Review by carver — APPROVED** [review]
LGTM!

**Comment by carver** [comment]
Can you ask devops to trigger a manual run of hive so we can get the hive results ASAP?

**Comment by KolbyML** [comment]
Yeah for sure

**Comment by KolbyML** [comment]
Ok I sent a dm so we will see what happens

**Pull request merged**
